annotations:
  artifacthub.io/images: |
    - name: feiyu563/prometheus-alert
      image: feiyu563/prometheus-alert:v4.9.2
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/dellnoantechnp.github.io/tree/main/charts/xxl-job-admin
apiVersion: v2
appVersion: v4.9.2
name: prometheusalert
description: A Alert-Center for Prometheus Grafana and Graylog, alert message deliver to Wechat/Feishu/Lark/email/DingTalk/workWechat/webhook/telegram ...
home: https://github.com/feiyu563/PrometheusAlert
icon: https://raw.githubusercontent.com/feiyu563/PrometheusAlert/master/doc/images/logo.png
maintainers:
- email: dellnoantechnp@gmail.com
  name: dellnoantechnp
  url: https://github.com/dellnoantechnp
sources:
- https://github.com/feiyu563/PrometheusAlert
type: application
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
version: 1.4.0