apiVersion: v2
name: cloudeye-exporter
description: Prometheus cloudeye exporter for Huaweicloud.
home: https://github.com/huaweicloud/cloudeye-exporter
annotations:
  ghcr.io/packages: |
    - name: dellnoantechnp/cloudeye-exporter
      image: dellnoantechnp/cloudeye-exporter:v2.0.31
  ghcr.io/license: Apache-2.0 license
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/dellnoantechnp/helm-chart-xxl-job-admin
sources:
  - https://github.com/dellnoantechnp/helm-chart-xxl-job-admin
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v2.0.31"

dependencies:
  - name: common
    repository: https://dellnoantechnp.github.io/helm-chart-xxl-job-admin/
    version: ^2.0.0

kubeVersion: ">=1.26.0-0"