## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.defaultStorageClass Global default StorageClass for Persistent Volume(s)
## @param global.storageClass DEPRECATED: use global.defaultStorageClass instead
## @param global.redis.password Global Redis(R) password (overrides `auth.password`)
## @param global.defaultFips Default value for the FIPS configuration (allowed values: '', restricted, relaxed, off). Can be overriden by the 'fips' object
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  defaultStorageClass: ""
  storageClass: ""
  ## Security parameters
  ##
  security:
    ## @param global.security.allowInsecureImages Allows skipping image verification
    allowInsecureImages: false
  redis:
    password: ""
  ##  Configure FIPS mode: '', 'restricted', 'relaxed', 'off'
  ##
  defaultFips: restricted

## Enable diagnostic mode in the deployment
##
diagnosticMode:
  ## @param diagnosticMode.enabled Enable diagnostic mode (all probes will be disabled and the command will be overridden)
  ##
  enabled: false
  ## @param diagnosticMode.command Command to override all containers in the deployment
  ##
  command:
    - sleep
  ## @param diagnosticMode.args Args to override all containers in the deployment
  ##
  args:
    - infinity

## Bitnami Redis(R) image
## ref: https://hub.docker.com/r/bitnami/redis/tags/
## @param image.registry [default: REGISTRY_NAME] Redis(R) image registry
## @param image.repository [default: REPOSITORY_NAME/redis] Redis(R) image repository
## @skip image.tag Redis(R) image tag (immutable tags are recommended)
## @param image.digest Redis(R) image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
## @param image.pullPolicy Redis(R) image pull policy
## @param image.pullSecrets Redis(R) image pull secrets
## @param image.debug Enable image debug mode
##
image:
  registry: fcr.fawve.cluster.ws
  repository: dellnoantechnp/dingtalk-bot
  tag: latest
  digest: ""
  ## Specify a imagePullPolicy
  ## ref: https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
  ##
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []
  ## Enable debug mode
  ##
  debug: false


containerPorts:
  http: 8000

replicaCount: 1

config:
  # argo-workflows config
  ARGO_WORKFLOWS_DOMAIN: https://workflows.example.com
  ARGO_WORKFLOWS_TOKEN: "xxx"
  ARGO_WORKFLOWS_WORKER_NAMESPACE: workflows

  # DingTalk IM config
  DINGTALK_CLIENT_ID: "xxx"
  DINGTALK_CLIENT_SECRET: "xxx"
  DINGTALK_ROBOT_CODE: "xxx"

  # Django debug
  DJANGO_DEBUG: false

## @param command Override default container command (useful when using custom images)
##
command: []
## @param args Override default container args (useful when using custom images)
##
args: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""



serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## Configure Pods Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param podSecurityContext.enabled Enabled Redis(R) master pods' Security Context
## @param podSecurityContext.fsGroupChangePolicy Set filesystem group change policy
## @param podSecurityContext.sysctls Set kernel settings using the sysctl interface
## @param podSecurityContext.supplementalGroups Set filesystem extra groups
## @param podSecurityContext.fsGroup Set Redis(R) master pod's Security Context fsGroup
##
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001
## Configure Container Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param containerSecurityContext.enabled Enabled Redis(R) master containers' Security Context
## @param containerSecurityContext.seLinuxOptions [object,nullable] Set SELinux options in container
## @param containerSecurityContext.runAsUser Set Redis(R) master containers' Security Context runAsUser
## @param containerSecurityContext.runAsGroup Set Redis(R) master containers' Security Context runAsGroup
## @param containerSecurityContext.runAsNonRoot Set Redis(R) master containers' Security Context runAsNonRoot
## @param containerSecurityContext.allowPrivilegeEscalation Is it possible to escalate Redis(R) pod(s) privileges
## @param containerSecurityContext.readOnlyRootFilesystem Set container's Security Context read-only root filesystem
## @param containerSecurityContext.seccompProfile.type Set Redis(R) master containers' Security Context seccompProfile
## @param containerSecurityContext.capabilities.drop Set Redis(R) master containers' Security Context capabilities to drop
##
containerSecurityContext:
  enabled: true
  seLinuxOptions: {}
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]

## @param master.hostAliases Redis(R) master pods host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []
## @param master.podLabels Extra labels for Redis(R) master pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}
## @param master.podAnnotations Annotations for Redis(R) master pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

## @param master.podAffinityPreset Pod affinity preset. Ignored if `master.affinity` is set. Allowed values: `soft` or `hard`
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAffinityPreset: ""
## @param master.podAntiAffinityPreset Pod anti-affinity preset. Ignored if `master.affinity` is set. Allowed values: `soft` or `hard`
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAntiAffinityPreset: soft
## Node master.affinity preset
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
##
nodeAffinityPreset:
  ## @param master.nodeAffinityPreset.type Node affinity preset type. Ignored if `master.affinity` is set. Allowed values: `soft` or `hard`
  ##
  type: ""
  ## @param master.nodeAffinityPreset.key Node label key to match. Ignored if `master.affinity` is set
  ##
  key: ""
  ## @param master.nodeAffinityPreset.values Node label values to match. Ignored if `master.affinity` is set
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []

## @param master.extraPodSpec Optionally specify extra PodSpec for the Redis(R) master pod(s)
##
extraPodSpec: {}

## @param priorityClassName dingtalk-bot pods' priorityClassName
##
priorityClassName: ""

## @param master.affinity Affinity for Redis(R) master pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## NOTE: `podAffinityPreset`, `podAntiAffinityPreset`, and `nodeAffinityPreset` will be ignored when it's set
##
affinity: {}
## @param master.nodeSelector Node labels for Redis(R) master pods assignment
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
##
nodeSelector: {}
## @param master.tolerations Tolerations for Redis(R) master pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
## @param master.topologySpreadConstraints Spread Constraints for Redis(R) master pod assignment
## ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
## E.g.
## topologySpreadConstraints:
##   - maxSkew: 1
##     topologyKey: node
##     whenUnsatisfiable: DoNotSchedule
##
topologySpreadConstraints: []

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

## Configure extra options for Redis(R) containers' liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
## @param master.startupProbe.enabled Enable startupProbe on Redis(R) master nodes
## @param master.startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
## @param master.startupProbe.periodSeconds Period seconds for startupProbe
## @param master.startupProbe.timeoutSeconds Timeout seconds for startupProbe
## @param master.startupProbe.failureThreshold Failure threshold for startupProbe
## @param master.startupProbe.successThreshold Success threshold for startupProbe
##
startupProbe:
  enabled: false
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
## @param master.livenessProbe.enabled Enable livenessProbe on Redis(R) master nodes
## @param master.livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
## @param master.livenessProbe.periodSeconds Period seconds for livenessProbe
## @param master.livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
## @param master.livenessProbe.failureThreshold Failure threshold for livenessProbe
## @param master.livenessProbe.successThreshold Success threshold for livenessProbe
##
livenessProbe:
  enabled: false
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
## @param master.readinessProbe.enabled Enable readinessProbe on Redis(R) master nodes
## @param master.readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
## @param master.readinessProbe.periodSeconds Period seconds for readinessProbe
## @param master.readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
## @param master.readinessProbe.failureThreshold Failure threshold for readinessProbe
## @param master.readinessProbe.successThreshold Success threshold for readinessProbe
##
readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5
## @param master.customStartupProbe Custom startupProbe that overrides the default one
##
customStartupProbe: {}
## @param master.customLivenessProbe Custom livenessProbe that overrides the default one
##
customLivenessProbe: {}
## @param master.customReadinessProbe Custom readinessProbe that overrides the default one
##
customReadinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true


redis:
  enabled: true

  replica:
    replicaCount: 1


redisExternal:
  enabled: false
  redisHost: "1.2.3.4"
  redisPort: 6379
  redisPassword: "password"
  redisDatabase: 1

  # redisUrl: redis://:password@host:port/1


metrics:
  enabled: true

  containerPorts:
    metrics: 8100